### ISSUE TITLE
error when calling HTTP.request

### ISSUE THREAD

**Issue by ThomasBreuer** [JuliaWeb/HTTP.jl#505]
Julia 1.3.0
HTTP.jl 0.8.8

The first example from HTTP's  `README.md` does not work in Julia 1.3.
```
julia> using HTTP

julia> r = HTTP.request("GET", "http://httpbin.org/ip")
ERROR: type Regex has no field match_data
```
As the message says, objects of type `Regex` have no field `:match_data` in Julia 1.3, but the code tries to access this field.
(The field had been available in earlier Julia versions.)

**Comment by ThomasBreuer** [comment]
I have cleaned my installation of Julia packages, and reinstalled everything again, including HTTP.jl.
Now the problem has vanished.
Sorry for the false alert.
