### ISSUE TITLE
`World age increment not at top level` precompilation error with Julia 1.12+

### ISSUE THREAD

**Issue by mortenpi** [JuliaWeb/HTTP.jl#1218]
Opening this mostly for visibility -- I _think_ this is a PrecompileTools regression (https://github.com/JuliaLang/PrecompileTools.jl/issues/58), but the syntax that causes it is a bit weird.

But HTTP fails to precompile on 1.12+ when using PrecompileTools 1.3.1 with:

```
Failed to precompile HTTP [cd3eb016-35fb-5094-929b-558a96fad6f3] to "/home/mortenpi/.julia/compiled/v1.12/HTTP/jl_evsPzI".
ERROR: LoadError: syntax: World age increment not at top level
Stacktrace:
  [1] top-level scope
    @ ~/oss/HTTP.jl/src/precompile.jl:3
  [2] include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./Base.jl:304
  [3] top-level scope
    @ ~/oss/HTTP.jl/src/HTTP.jl:643
  [4] include(mod::Module, _path::String)
    @ Base ./Base.jl:303
  [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:3015
  [6] top-level scope
    @ stdin:5
  [7] eval(m::Module, e::Any)
    @ Core ./boot.jl:489
  [8] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:2861
  [9] include_string
    @ ./loading.jl:2871 [inlined]
 [10] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:326
 [11] _start()
    @ Base ./client.jl:560
in expression starting at /home/mortenpi/oss/HTTP.jl/src/precompile.jl:3
in expression starting at /home/mortenpi/oss/HTTP.jl/src/HTTP.jl:1
in expression starting at stdin:
```

It seems to be due to the `withenv` around `@compile_workload` (see the MWE in the linked issue): https://github.com/JuliaWeb/HTTP.jl/blob/9db9aaded7c942e442b185d03ea5fd212b1b7efe/src/precompile.jl#L34-L38

**Comment by jpthiele** [comment]
> The `withenv` will have to go inside the `@compile_workload` if you want high-quality precompilation. You can't put `@compile_workload` inside a thunk and expect Julia to defer compiling anything until after turning on compile-tracing.

I'm not familiar enough with the inner workings of precompilation.
Would this change fix the bug or is this mainly for optimizing precompilation?

**Comment by timholy** [comment]
Both (it should fix the bug *and* improve your precompilation)

**Comment by IanButterworth** [comment]
Would it be possible for PrecompileTools to detect when it's being used in an already compiled thunk?

**Comment by KristofferC** [comment]
Because it was introduced by a recent change in PrecompileTools.

**Comment by timholy** [comment]
> Would it be possible for PrecompileTools to detect when it's being used in an already compiled thunk?

https://github.com/JuliaLang/PrecompileTools.jl/pull/60 now uses `Expr(Symbol("latestworld-if-toplevel"))`. I didn't know that existed until Keno pointed it out. It would make your https://github.com/JuliaLang/julia/pull/58015 far simpler, you could just put it straight in the macro.
